
security:
  jwt:
    signature: ${SIGNATURE}

url:
  base: http://localhost:8080
  resource:
    confirmation: /api/v1/confirmation

spring:
  datasource:
    name: rotas_db
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    from: ${EMAIL_USERNAME}
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true