
security:
  jwt:
    signature: ${SIGNATURE}

url:
  base: http://localhost:8080
  resource:
    account:
      confirm: /api/v1/account/email-confirmation
      delete: /api/v1/account/delete
    driver:
      create: /api/v1/drivers
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    name: rotas_db
    url: jdbc:h2:mem:routes_test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    from: ${EMAIL_USERNAME}
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true