
security:
  jwt:
    signature: ${SIGNATURE}

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:routes_test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # driver-class-name: org.postgresql.Driver
    name: rotas_db
    # password: ${DATABASE_PASSWORD}
    # username: ${DATABASE_USERNAME}
    # url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update